// To exclude a photo, prefix its line with // — to include, remove the //.
// Order in the array = order in the lightbox.

const make = (dir) => (file) => `images/${dir}/${file}`;

const sf = make('sf');
const ahm = make('ahmedabad');
const atl = make('atitlan');
const acadia = make('acadia');
const antigua = make('antigua');
const baylands = make('baylands');
const davenport = make('davenport');
const hallstatt = make('hallstatt');
const hmb = make('hmb');
const lah = make('lah');
const napa = make('napa');
const nyc = make('nyc');
const paFarm = make('pa-farm');
const pittsburgh = make('pittsburgh');
const salzburg = make('salzburg');
const santaCruz = make('santa-cruz');
const tahoe = make('tahoe');
const villanova = make('villanova');
const yosemite = make('yosemite');

export const locations = [
  {
    id: 'sf',
    name: 'San Francisco',
    lat: 37.7749,
    lng: -122.4194,
    photos: [
      sf('chinatown-man-lurking.jpg'),
      sf('ferry-building-interior.jpg'),
      sf('fillmore-colorful-rooms.jpg'),
      // sf('japanese-tea-garden-bamboo.jpg'),
      // sf('japanese-tea-garden-koi-fish.jpg'),
      sf('japanese-tea-garden-yellow-tree-by-bridge.jpg'),
      sf('lafayette-park-caution-plants.jpg'),
      // sf('lafayette-park-ria-mihir.jpg'),
      // sf('lafayette-park-sunset.jpg'),
      sf('orange-beige-movie-theater.jpg'),
      // sf('rohan-yerba-buena-park-1.jpg'),
      // sf('rohan-yerba-buena-park-2.jpg'),
      sf('slanted-porta-potty.jpg'),
    ],
  },
  {
    id: 'ahmedabad',
    name: 'Ahmedabad',
    lat: 23.0225,
    lng: 72.5714,
    photos: [
      ahm('under-the-neem-tree.jpg'),
      ahm('woman-and-bulls-janak-farm.jpg'),
      ahm('retro-radio.jpg'),
      ahm('bull-courtyard-by-mariott.jpg'),
      ahm('crow-in-tree.jpg'),
      ahm('dadi-amul-busy-street.jpg'),
      ahm('dadi-at-dannys.jpg'),
      ahm('dadi-hailing-a-rickshaw.jpg'),
      ahm('dadi-outside-her-apartment.jpg'),
      ahm('dadi-walking-out-of-apartment.jpg'),
      ahm('dadis-apartment-pipes.jpg'),
      ahm('dadis-hands-fruit-stand.jpg'),
      // ahm('entrance-to-janak-farmhouse.jpg'),
      ahm('janak-farm-log-between-two-trees.jpg'),
      // ahm('janak-farm-pool-house-and-lake.jpg'),
      // ahm('janak-farmhouse-navratri-garba-bug-repellent-smoke.jpg'),
      ahm('janak-farmhouse.jpg'),
      ahm('manekchowk-fabrics.jpg'),
      ahm('manekchowk-fresh-fruits.jpg'),
      ahm('manekchowk-man-in-mosque.jpg'),
      ahm('monkey-outside-dadis-place.jpg'),
      ahm('nun-outside-dadis-apartment.jpg'),
      // ahm('pigeons-in-flight-near-dannys.jpg'),
      // ahm('sunset-red-lights.jpg'),
      ahm('two-sets-of-three-navrangpura-street.jpg'),
      ahm('uber-rickshaw.jpg'),
      // ahm('under-the-neem-tree---processed---matte-print.jpg'), // duplicate of above (matte print variant)
      // ahm('white-bird-at-janak-farm.jpg'),
    ],
  },
  {
    id: 'atitlan',
    name: 'Lake Atitlán',
    lat: 14.6911,
    lng: -91.2025,
    photos: [
      // atl('ria.jpg'),
      // atl('rohan-1.jpg'),
      // atl('rohan-2.jpg'),
      atl('solo-man-rowboat.jpg'),
      atl('solo-boat.jpg'),
    ],
  },
  {
    id: 'acadia',
    name: 'Acadia National Park',
    lat: 44.3386,
    lng: -68.2733,
    photos: [
      acadia('acadia-collage.jpg'),
      acadia('acadia-collage-2.jpg'),
      acadia('acadia-trees.jpg'),
      acadia('acadia-trees-light.jpg'),
      acadia('colors.jpg'),
      acadia('colors-2.jpg'),
      acadia('colors-3.jpg'),
      acadia('colors-4.jpg'),
      acadia('rohan-acadia.jpg'),
    ],
  },
  {
    id: 'antigua',
    name: 'Antigua, Guatemala',
    lat: 14.5586,
    lng: -90.7295,
    photos: [
      antigua('housing-complex-reflection.jpg'),
      antigua('housing-complex-volcano.jpg'),
      antigua('yellow-threshold-reflection.jpg'),
    ],
  },
  {
    id: 'baylands',
    name: 'Palo Alto Baylands',
    lat: 37.4530,
    lng: -122.1056,
    photos: [
      baylands('bird-structures.jpg'),
      baylands('mummy-and-lu.jpg'),
      baylands('mummy-wildflowers.jpg'),
      baylands('yellow-flowers-reflection.jpg'),
      baylands('yellow-wildflowers.jpg'),
      baylands('yellow-wildflowers-bee.jpg'),
    ],
  },
  {
    id: 'davenport',
    name: 'Davenport',
    lat: 37.0086,
    lng: -122.1942,
    photos: [
      davenport('ethan.jpg'),
      davenport('factory-framed-by-trees.jpg'),
      davenport('floating-tree.jpg'),
      davenport('foam-and-moss-1.jpg'),
      davenport('foam-and-moss-2.jpg'),
      davenport('from-above.jpg'),
      davenport('ishaan-radhika.jpg'),
      davenport('ishaan-tree-frame.jpg'),
      davenport('ocean-structure.jpg'),
      davenport('painted-tree.jpg'),
      davenport('path.jpg'),
      davenport('rv-factory.jpg'),
      davenport('trees-ocean.jpg'),
      davenport('trees-structure-yellow-flowers-1.jpg'),
      davenport('trees-structure-yellow-flowers-2.jpg'),
      davenport('white-flower-trail.jpg'),
      davenport('yellow-flowers.jpg'),
    ],
  },
  {
    id: 'hallstatt',
    name: 'Hallstatt',
    lat: 47.5622,
    lng: 13.6493,
    photos: [
      hallstatt('alps-roofline.jpg'),
      hallstatt('black-llama.jpg'),
      hallstatt('castle-across-the-lake.jpg'),
      hallstatt('diving-board.jpg'),
      hallstatt('ducks-underwater-net.jpg'),
      hallstatt('ethan-rohan-top-of-mountain.jpg'),
      hallstatt('lake-town-mountains.jpg'),
      hallstatt('rohan-top-of-mountain.jpg'),
      hallstatt('tree-like-a-vine.jpg'),
      hallstatt('wooden-homes.jpg'),
    ],
  },
  {
    id: 'hmb',
    name: 'Half Moon Bay',
    lat: 37.4636,
    lng: -122.4286,
    photos: [
      hmb('ocean-and-rocks.jpg'),
      hmb('pink-wildflowers-ocean.jpg'),
      hmb('yellow-wildflowers.jpg'),
    ],
  },
  {
    id: 'lah',
    name: 'Los Altos Hills',
    lat: 37.3819,
    lng: -122.1376,
    photos: [
      lah('blurry-tree.jpg'),
      lah('blurry-tree-and-signs.jpg'),
      lah('deer-byrne-preserve.jpg'),
      lah('horse-amigo.jpg'),
      lah('horse-stall.jpg'),
      lah('ishaan-byrne-preserve.jpg'),
      lah('modern-house-old-fence-lah.jpg'),
      lah('natasha-horse-byrne-preserve.jpg'),
      lah('old-house-bathtub-virgin-mary.jpg'),
      lah('orange-flowers-byrne-preserve.jpg'),
      lah('orange-tree-moss.jpg'),
      lah('seesaw.jpg'),
      lah('westwind-barn-long-exposure.jpg'),
    ],
  },
  {
    id: 'napa',
    name: 'Napa',
    lat: 38.2975,
    lng: -122.2869,
    photos: [
      napa('larissa-ananya-natasha.jpg'),
      napa('larissa-natasha-foy-napa.jpg'),
      napa('natasha-foy-vineyard.jpg'),
    ],
  },
  {
    id: 'nyc',
    name: 'New York City',
    lat: 40.7128,
    lng: -74.0060,
    photos: [
      nyc('dumbo-nana-raj-nani-indian-food.jpg'),
      nyc('dumbo-nani-in-red.jpg'),
      nyc('dumbo-nani-nana-brooklyn-bridge.jpg'),
      nyc('tribeca-bhav-double-hockey-sticks.jpg'),
    ],
  },
  {
    id: 'pa-farm',
    name: 'Pennsylvania',
    lat: 41.2033,
    lng: -77.1945,
    photos: [
      paFarm('fam-at-farm.jpg'),
      paFarm('farmhouse.jpg'),
    ],
  },
  {
    id: 'pittsburgh',
    name: 'Pittsburgh',
    lat: 40.4406,
    lng: -79.9959,
    photos: [
      pittsburgh('ashwin-boonseek.jpg'),
      pittsburgh('ashwin-fif-munching.jpg'),
      pittsburgh('beeler-tlee-mirror-dusk-1.jpg'),
      pittsburgh('beeler-tlee-mirror-dusk-2.jpg'),
      pittsburgh('bhav-crossing-beeler-1.jpg'),
      pittsburgh('bhav-crossing-beeler-2.jpg'),
      pittsburgh('bhav-heel-click-1.jpg'),
      pittsburgh('bhav-heel-click-2.jpg'),
      pittsburgh('bhav-manel-working-upstairs.jpg'),
      pittsburgh('bhav-sanch-manel-beeler.jpg'),
      pittsburgh('bhav-thrift-store.jpg'),
      pittsburgh('bhav-uc-staircase.jpg'),
      pittsburgh('bhav-working-upstairs.jpg'),
      pittsburgh('blue-bus-ahmed-jackson-ishan-1.jpg'),
      pittsburgh('blue-bus-ahmed-jackson-ishan-2.jpg'),
      pittsburgh('blue-light-exp-chair-and-rick.jpg'),
      pittsburgh('butterjoint-low-light.jpg'),
      pittsburgh('carter-studying-beeler.jpg'),
      pittsburgh('carter-studying-dusk-1.jpg'),
      pittsburgh('carter-studying-dusk-2.jpg'),
      pittsburgh('cathedral-mansions-entrance.jpg'),
      pittsburgh('cathedral-mansions-windowsill.jpg'),
      pittsburgh('church-ethan-lucy.jpg'),
      pittsburgh('clyde-street-dusk-light.jpg'),
      pittsburgh('dusk-on-beeler.jpg'),
      pittsburgh('ethan-in-shower-full-body.jpg'),
      pittsburgh('ethan-in-shower-headon.jpg'),
      pittsburgh('hannah-anya-thrift-store.jpg'),
      pittsburgh('hannah-thrift-store.jpg'),
      pittsburgh('house-5218-5-foil.jpg'),
      pittsburgh('house-blue-and-red.jpg'),
      pittsburgh('ishan-crossing-biker.jpg'),
      pittsburgh('jackson-danny-halloween-laughing.jpg'),
      pittsburgh('jackson-fall-1.jpg'),
      pittsburgh('jackson-fall-2.jpg'),
      pittsburgh('jackson-halloween-laughing.jpg'),
      pittsburgh('jacob-ahmed-ishan-danny.jpg'),
      pittsburgh('jacob-jackson-manel-anya-ishan-tlee.jpg'),
      pittsburgh('manel-anya-thrift-store.jpg'),
      pittsburgh('manel-tlee-embrace.jpg'),
      pittsburgh('manel-tlee-ishan-jackson-bhav-thrift-store-1.jpg'),
      pittsburgh('manel-tlee-ishan-jackson-bhav-thrift-store-2.jpg'),
      pittsburgh('manel-tlee-ishan-jackson-bhav-thrift-store-3.jpg'),
      pittsburgh('mother-son-outside-uc.jpg'),
      pittsburgh('orange-green-contrast-tepper-reflection.jpg'),
      pittsburgh('orange-tree-cmu-volleyball-court.jpg'),
      pittsburgh('pillars-of-gates-and-stop-sign.jpg'),
      pittsburgh('southside-carter-hannah-1.jpg'),
      pittsburgh('southside-carter-hannah-2.jpg'),
      pittsburgh('southside-gwagon.jpg'),
      pittsburgh('southside-manel-1.jpg'),
      pittsburgh('southside-manel-2.jpg'),
      pittsburgh('southside-manel-3.jpg'),
      pittsburgh('southside-manel-anya.jpg'),
      pittsburgh('tepper-lower-level-exterior.jpg'),
      pittsburgh('tepper-lower-lot.jpg'),
      pittsburgh('tepper-quad-stone-orange-tape.jpg'),
      pittsburgh('three-rivers-bridge-road-sign.jpg'),
      pittsburgh('three-rivers-point-arch.jpg'),
      pittsburgh('three-rivers-point-bridge.jpg'),
      pittsburgh('three-rivers-point-bridge-reflection.jpg'),
      pittsburgh('tlee-bhav-manel-danny.jpg'),
      pittsburgh('tlee-demonic.jpg'),
      pittsburgh('tlee-ishan.jpg'),
      pittsburgh('tree-by-cmu-soccer-field-1-photo-response.jpg'),
      pittsburgh('tree-by-cmu-soccer-field-2-photo-response.jpg'),
      pittsburgh('tree-by-cmu-soccer-field-3-photo-response.jpg'),
      pittsburgh('two-orange-jumpsuits-1.jpg'),
      pittsburgh('two-orange-jumpsuits-2.jpg'),
      pittsburgh('yellow-flowers-on-beeler-street.jpg'),
    ],
  },
  {
    id: 'salzburg',
    name: 'Salzburg',
    lat: 47.8095,
    lng: 13.0550,
    photos: [
      salzburg('dusk-fortress-hohensalzburg.jpg'),
      salzburg('green-and-pink-pastel-buildings.jpg'),
      salzburg('hotel-clock-tower.jpg'),
    ],
  },
  {
    id: 'santa-cruz',
    name: 'Santa Cruz',
    lat: 37.0117,
    lng: -122.0308,
    photos: [
      santaCruz('park-electricity-pole-landscape.jpg'),
    ],
  },
  {
    id: 'tahoe',
    name: 'Lake Tahoe',
    lat: 39.0968,
    lng: -120.0324,
    photos: [
      tahoe('americas-best-beware-of-trains.jpg'),
      tahoe('americas-best-snowy-playground-lake.jpg'),
      tahoe('americas-best-two-chairs.jpg'),
    ],
  },
  {
    id: 'villanova',
    name: 'Villanova',
    lat: 40.0387,
    lng: -75.3438,
    photos: [
      villanova('ac-outside-lab.jpg'),
      villanova('indoor-outdoor.jpg'),
      villanova('trees.jpg'),
      villanova('white-flowers-fence.jpg'),
    ],
  },
  {
    id: 'yosemite',
    name: 'Yosemite',
    lat: 37.8651,
    lng: -119.5383,
    photos: [
      yosemite('horse-by-stream.jpg'),
      yosemite('pink-flowers.jpg'),
      yosemite('porsche.jpg'),
      yosemite('ronit-ishaan-adam-ethan.jpg'),
      yosemite('stream-and-mountain.jpg'),
      yosemite('stream-blur-1.jpg'),
      yosemite('stream-blur-2.jpg'),
      yosemite('tree-trunk-and-yellow-flowers.jpg'),
    ],
  },
];
